<?php


namespace App\Models;


use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class BaseModel extends Model
{
    public function toArray()
    {
        $array = [];
        foreach (parent::toArray() as $key => $value) {
            $array[Str::camel($key)] = $value;
        }
        return $array;
    }

    public function getAttribute($key)
    {
        if (array_key_exists($key, $this->relations) || method_exists($this, $key)) {
            return parent::getAttribute($key);
        } else {
            return parent::getAttribute(Str::snake($key));
        }
    }

    public function setAttribute($key, $value)
    {
        return parent::setAttribute(Str::snake($key), $value);
    }

    public function __isset($key)
    {
        return parent::__isset($key) || parent::__isset(Str::snake($key)); // TODO: Change the autogenerated stub
    }

    public function __unset($key)
    {
        parent::__unset($key);
        parent::__unset(Str::snake($key));
    }
}
